import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import TanstackQueryProvider from '@/lib/providers/TanstackQueryProvider';
import ToastContainerProvider from '@/lib/providers/ToastContainerProvider';
import './globals.css';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <TanstackQueryProvider>
            <Suspense>{children} </Suspense>
          </TanstackQueryProvider>

          <ToastContainerProvider />
        </main>
      </body>
    </html>
  );
}
